apiVersion: apps/v1 
kind: Deployment    
metadata:              
  name: springboot-userinfo
spec:                
  selector:         
    matchLabels:
      app: springboot-userinfo
  replicas: 1        
  template:
    metadata:
      labels:        
        app: springboot-userinfo
    spec:
      containers:
        - name: springboot-userinfo-container
          image: rohitsutar/userinfo-springboot:v1
          ports:
            - containerPort: 8080                
          env:   # Setting Enviornmental Variables
          - name: DB_HOST   # Setting Database host address from configMap
            valueFrom: 
              configMapKeyRef:
                name: hostname-dbname-config  # name of configMap
                key: host
          - name: DB_NAME  # Setting Database name from configMap
            valueFrom:
              configMapKeyRef:
                name: hostname-dbname-config
                key: name
          - name: DB_USERNAME  # Setting Database username from Secret
            valueFrom:
              secretKeyRef:
                name: db-nonroot-user-credentials # Secret Name
                key: username
          - name: DB_PASSWORD # Setting Database password from Secret
            valueFrom:
              secretKeyRef:
                name: db-nonroot-user-credentials
                key: password 
